from pandas import DataFrame
from data_transformers import chain, transformer


#  DEFINITIONS_START
@transformer.convert
def query(df: DataFrame, condition: str):
    df = df.query(condition)    
    return df

@transformer.convert
def drop_col(df: DataFrame, col, axis=1):
    return df.drop(col, axis=axis)

@transformer.convert
def add_nombre_corto(df: DataFrame, col:str):

    import pandas as pd

    # Realiza un join entre el DataFrame original y el geonomenclador
    geonomenclador = pd.DataFrame({
    "geocodigo": [
        "ABW",
        "AFE",
        "AFG",
        "AFW",
        "AGO",
        "AIA",
        "ALA",
        "ALB",
        "AND",
        "ANT",
        "ARB",
        "ARE",
        "ARG",
        "ARM",
        "ASM",
        "ATA",
        "ATF",
        "ATG",
        "AUS",
        "AUT",
        "AZE",
        "BAT",
        "BDI",
        "BEL",
        "BEN",
        "BES",
        "BFA",
        "BGD",
        "BGR",
        "BHR",
        "BHS",
        "BIH",
        "BLM",
        "BLR",
        "BLX",
        "BLZ",
        "BMU",
        "BOL",
        "BRA",
        "BRB",
        "BRN",
        "BTN",
        "BVT",
        "BWA",
        "CAF",
        "CAN",
        "CCK",
        "CEB",
        "CEM",
        "CHE",
        "CHI",
        "CHL",
        "CHN",
        "CIV",
        "CMR",
        "COD",
        "COG",
        "COK",
        "COL",
        "COM",
        "CPV",
        "CRI",
        "CSK",
        "CSS",
        "CUB",
        "CUW",
        "CXR",
        "CYM",
        "CYP",
        "CZE",
        "DDR",
        "DEU",
        "DJI",
        "DMA",
        "DNK",
        "DOM",
        "DZA",
        "EAP",
        "EAR",
        "EAS",
        "ECA",
        "ECS",
        "ECU",
        "EGY",
        "EMU",
        "ERI",
        "ESH",
        "ESP",
        "EST",
        "ETF",
        "ETH",
        "EUU",
        "F164",
        "F206",
        "F285",
        "F336",
        "F351",
        "F420",
        "F429",
        "F5101",
        "F5102",
        "F5103",
        "F5104",
        "F5105",
        "F5203",
        "F5204",
        "F5205",
        "F5206",
        "F5207",
        "F5208",
        "F5300",
        "F5301",
        "F5302",
        "F5303",
        "F5304",
        "F5305",
        "F5306",
        "F5307",
        "F5308",
        "F5401",
        "F5402",
        "F5403",
        "F5404",
        "F5500",
        "F5501",
        "F5502",
        "F5504",
        "F5600",
        "F5707",
        "F5801",
        "F5802",
        "F5803",
        "F5807",
        "F5810",
        "F5815",
        "F5817",
        "F5825",
        "F5826",
        "F5827",
        "F5828",
        "F5829",
        "F5848",
        "F5849",
        "F5855",
        "F5857",
        "F5858",
        "F5859",
        "F5873",
        "F62",
        "F78",
        "F9010",
        "F9011",
        "FCS",
        "FIN",
        "FJI",
        "FLK",
        "FRA",
        "FRE",
        "FRO",
        "FSM",
        "GAB",
        "GAZ",
        "GBR",
        "GEO",
        "GGY",
        "GHA",
        "GIB",
        "GIN",
        "GLP",
        "GMB",
        "GNB",
        "GNQ",
        "GRC",
        "GRD",
        "GRL",
        "GTM",
        "GUF",
        "GUM",
        "GUY",
        "HIC",
        "HKG",
        "HMD",
        "HND",
        "HPC",
        "HRV",
        "HTI",
        "HUN",
        "IBD",
        "IBT",
        "IDA",
        "IDB",
        "IDN",
        "IDX",
        "IMN",
        "IND",
        "IOT",
        "IRL",
        "IRN",
        "IRQ",
        "ISL",
        "ISR",
        "ITA",
        "JAM",
        "JEY",
        "JOR",
        "JPN",
        "JTN",
        "KAZ",
        "KEN",
        "KGZ",
        "KHM",
        "KIR",
        "KN1",
        "KNA",
        "KOR",
        "KWT",
        "LAC",
        "LAO",
        "LBN",
        "LBR",
        "LBY",
        "LCA",
        "LCN",
        "LDC",
        "LIC",
        "LIE",
        "LKA",
        "LMC",
        "LMY",
        "LSO",
        "LTE",
        "LTU",
        "LUX",
        "LVA",
        "MAC",
        "MAF",
        "MAR",
        "MCO",
        "MDA",
        "MDG",
        "MDV",
        "MEA",
        "MEX",
        "MHL",
        "MIC",
        "MID",
        "MKD",
        "MLI",
        "MLT",
        "MMR",
        "MNA",
        "MNE",
        "MNG",
        "MNP",
        "MOZ",
        "MRT",
        "MSR",
        "MTQ",
        "MUS",
        "MWI",
        "MYS",
        "MYT",
        "NAC",
        "NAM",
        "NCL",
        "NER",
        "NFK",
        "NGA",
        "NIC",
        "NIU",
        "NLD",
        "NOR",
        "NPL",
        "NRU",
        "NZE",
        "NZL",
        "OED",
        "OHI",
        "OMN",
        "OSS",
        "PAK",
        "PAN",
        "PCE",
        "PCN",
        "PCZ",
        "PER",
        "PHL",
        "PLW",
        "PMY",
        "PNG",
        "POL",
        "PRE",
        "PRI",
        "PRK",
        "PRT",
        "PRY",
        "PSE",
        "PSS",
        "PST",
        "PYF",
        "QAT",
        "REU",
        "ROU",
        "RUS",
        "RWA",
        "RYU",
        "SAS",
        "SAU",
        "SBH",
        "SCG",
        "SDN",
        "SEN",
        "SER",
        "SGP",
        "SGS",
        "SHN",
        "SIK",
        "SJM",
        "SLB",
        "SLE",
        "SLV",
        "SMR",
        "SOM",
        "SPE",
        "SPM",
        "SRB",
        "SSA",
        "SSD",
        "SSF",
        "SST",
        "STP",
        "SUR",
        "SVK",
        "SVN",
        "SVR",
        "SVU",
        "SWE",
        "SWK",
        "SWZ",
        "SXM",
        "SYC",
        "SYR",
        "TAN",
        "TCA",
        "TCD",
        "TEA",
        "TEC",
        "TGO",
        "THA",
        "TJK",
        "TKL",
        "TKM",
        "TLA",
        "TLS",
        "TMN",
        "TON",
        "TSA",
        "TSS",
        "TTO",
        "TUN",
        "TUR",
        "TUV",
        "TWN",
        "TZA",
        "UGA",
        "UKR",
        "UMC",
        "UMI",
        "UNS",
        "URY",
        "USA",
        "USP",
        "UZB",
        "VAT",
        "VCT",
        "VDR",
        "VEN",
        "VGB",
        "VIR",
        "VNM",
        "VUT",
        "WAK",
        "WBG",
        "WLD",
        "WLF",
        "WSM",
        "X06",
        "X21",
        "XKX",
        "YDR",
        "YEM",
        "YMD",
        "ZAF",
        "ZMB",
        "ZPM",
        "ZW1",
        "ZWE",
        "OWID_USS",
        "TRANS",
        "PCI",
        "ANS",
        "APEC",
        "ASEAN",
        "EA19",
        "EASIA",
        "EU13",
        "EU15",
        "EU27_2020",
        "EU28",
        "G20",
        "NONOECD",
        "OECD",
        "ROW",
        "ZASI",
        "ZEUR",
        "ZNAM",
        "ZOTH",
        "ZSCA",
        "OWID_AKD",
        "AR-C",
        "AR-B",
        "AR-K",
        "AR-X",
        "AR-W",
        "AR-H",
        "AR-U",
        "AR-E",
        "AR-P",
        "AR-Y",
        "AR-L",
        "AR-F",
        "AR-M",
        "AR-N",
        "AR-Q",
        "AR-R",
        "AR-A",
        "AR-J",
        "AR-D",
        "AR-Z",
        "AR-S",
        "AR-G",
        "AR-T",
        "AR-V",
        "AR-C001",
        "AR-C002",
        "AR-C003",
        "AR-C004",
        "AR-C005",
        "AR-C006",
        "AR-C007",
        "AR-C008",
        "AR-C009",
        "AR-C010",
        "AR-C011",
        "AR-C012",
        "AR-C013",
        "AR-C014",
        "AR-C015",
        "AR-B007",
        "AR-B021",
        "AR-B028",
        "AR-B035",
        "AR-B042",
        "AR-B049",
        "AR-B056",
        "AR-B063",
        "AR-B070",
        "AR-B077",
        "AR-B091",
        "AR-B098",
        "AR-B105",
        "AR-B112",
        "AR-B119",
        "AR-B126",
        "AR-B134",
        "AR-B140",
        "AR-B147",
        "AR-B154",
        "AR-B161",
        "AR-B602",
        "AR-B168",
        "AR-B175",
        "AR-B189",
        "AR-B196",
        "AR-B182",
        "AR-B203",
        "AR-B210",
        "AR-B217",
        "AR-B224",
        "AR-B231",
        "AR-B238",
        "AR-B245",
        "AR-B252",
        "AR-B260",
        "AR-B266",
        "AR-B274",
        "AR-B280",
        "AR-B287",
        "AR-B294",
        "AR-B301",
        "AR-B308",
        "AR-B322",
        "AR-B329",
        "AR-B336",
        "AR-B315",
        "AR-B343",
        "AR-B351",
        "AR-B357",
        "AR-B364",
        "AR-B371",
        "AR-B760",
        "AR-B385",
        "AR-B392",
        "AR-B014",
        "AR-B399",
        "AR-B406",
        "AR-B084",
        "AR-B413",
        "AR-B427",
        "AR-B434",
        "AR-B441",
        "AR-B448",
        "AR-B455",
        "AR-B462",
        "AR-B469",
        "AR-B476",
        "AR-B483",
        "AR-B490",
        "AR-B497",
        "AR-B505",
        "AR-B511",
        "AR-B518",
        "AR-B525",
        "AR-B532",
        "AR-B539",
        "AR-B547",
        "AR-B560",
        "AR-B568",
        "AR-B574",
        "AR-B581",
        "AR-B588",
        "AR-B595",
        "AR-B609",
        "AR-B616",
        "AR-B623",
        "AR-B630",
        "AR-B638",
        "AR-B644",
        "AR-B651",
        "AR-B658",
        "AR-B665",
        "AR-B672",
        "AR-B679",
        "AR-B686",
        "AR-B693",
        "AR-B700",
        "AR-B707",
        "AR-B721",
        "AR-B714",
        "AR-B728",
        "AR-B735",
        "AR-B742",
        "AR-B749",
        "AR-B756",
        "AR-B763",
        "AR-B770",
        "AR-B778",
        "AR-B784",
        "AR-B791",
        "AR-B798",
        "AR-B805",
        "AR-B819",
        "AR-B826",
        "AR-B812",
        "AR-B833",
        "AR-B840",
        "AR-B420",
        "AR-B553",
        "AR-B854",
        "AR-B861",
        "AR-B868",
        "AR-B875",
        "AR-B882",
        "AR-B847",
        "AR-B277",
        "AR-B648",
        "AR-B412",
        "AR-B515",
        "AR-B655",
        "AR-B270",
        "AR-B410",
        "AR-B408",
        "AR-B466",
        "AR-K049",
        "AR-K042",
        "AR-K070",
        "AR-K014",
        "AR-K056",
        "AR-K098",
        "AR-K077",
        "AR-K112",
        "AR-K063",
        "AR-K007",
        "AR-K084",
        "AR-K021",
        "AR-K035",
        "AR-K028",
        "AR-K105",
        "AR-K091",
        "AR-X014",
        "AR-X007",
        "AR-X021",
        "AR-X028",
        "AR-X035",
        "AR-X042",
        "AR-X049",
        "AR-X056",
        "AR-X063",
        "AR-X070",
        "AR-X077",
        "AR-X091",
        "AR-X098",
        "AR-X105",
        "AR-X112",
        "AR-X119",
        "AR-X084",
        "AR-X126",
        "AR-X133",
        "AR-X140",
        "AR-X147",
        "AR-X154",
        "AR-X161",
        "AR-X168",
        "AR-X175",
        "AR-X182",
        "AR-W021",
        "AR-W070",
        "AR-W035",
        "AR-W105",
        "AR-W049",
        "AR-W091",
        "AR-W168",
        "AR-W119",
        "AR-W112",
        "AR-W140",
        "AR-W007",
        "AR-W042",
        "AR-W161",
        "AR-W063",
        "AR-W126",
        "AR-W147",
        "AR-W028",
        "AR-W098",
        "AR-W084",
        "AR-W175",
        "AR-W133",
        "AR-W056",
        "AR-W154",
        "AR-W077",
        "AR-W014",
        "AR-H140",
        "AR-H126",
        "AR-H077",
        "AR-H056",
        "AR-H154",
        "AR-H119",
        "AR-H014",
        "AR-H084",
        "AR-H161",
        "AR-H147",
        "AR-H098",
        "AR-H112",
        "AR-H021",
        "AR-H133",
        "AR-H168",
        "AR-H091",
        "AR-H070",
        "AR-H049",
        "AR-H105",
        "AR-H028",
        "AR-H036",
        "AR-H039",
        "AR-H043",
        "AR-H007",
        "AR-H063",
        "AR-U077",
        "AR-U007",
        "AR-U105",
        "AR-U049",
        "AR-U014",
        "AR-U035",
        "AR-U056",
        "AR-U098",
        "AR-U070",
        "AR-U063",
        "AR-U028",
        "AR-U042",
        "AR-U084",
        "AR-U091",
        "AR-U021",
        "AR-E084",
        "AR-E070",
        "AR-E021",
        "AR-E105",
        "AR-E077",
        "AR-E049",
        "AR-E091",
        "AR-E098",
        "AR-E056",
        "AR-E063",
        "AR-E113",
        "AR-E015",
        "AR-E035",
        "AR-E008",
        "AR-E042",
        "AR-E028",
        "AR-E088",
        "AR-P014",
        "AR-P021",
        "AR-P049",
        "AR-P056",
        "AR-P042",
        "AR-P035",
        "AR-P007",
        "AR-P028",
        "AR-P063",
        "AR-Y021",
        "AR-Y042",
        "AR-Y056",
        "AR-Y014",
        "AR-Y063",
        "AR-Y070",
        "AR-Y035",
        "AR-Y105",
        "AR-Y098",
        "AR-Y094",
        "AR-Y028",
        "AR-Y007",
        "AR-Y049",
        "AR-Y077",
        "AR-Y112",
        "AR-Y084",
        "AR-L007",
        "AR-L021",
        "AR-L014",
        "AR-L028",
        "AR-L049",
        "AR-L056",
        "AR-L063",
        "AR-L035",
        "AR-L042",
        "AR-L070",
        "AR-L077",
        "AR-L098",
        "AR-L084",
        "AR-L091",
        "AR-L105",
        "AR-L112",
        "AR-L119",
        "AR-L126",
        "AR-L133",
        "AR-L140",
        "AR-L147",
        "AR-L154",
        "AR-F014",
        "AR-F126",
        "AR-F021",
        "AR-F007",
        "AR-F119",
        "AR-F042",
        "AR-F049",
        "AR-F028",
        "AR-F077",
        "AR-F098",
        "AR-F105",
        "AR-F035",
        "AR-F056",
        "AR-F063",
        "AR-F070",
        "AR-F084",
        "AR-F112",
        "AR-F091",
        "AR-M007",
        "AR-M021",
        "AR-M028",
        "AR-M049",
        "AR-M056",
        "AR-M070",
        "AR-M063",
        "AR-M126",
        "AR-M098",
        "AR-M035",
        "AR-M084",
        "AR-M119",
        "AR-M091",
        "AR-M112",
        "AR-M042",
        "AR-M105",
        "AR-M077",
        "AR-M014",
        "AR-N028",
        "AR-N007",
        "AR-N021",
        "AR-N070",
        "AR-N035",
        "AR-N105",
        "AR-N098",
        "AR-N091",
        "AR-N077",
        "AR-N014",
        "AR-N119",
        "AR-N084",
        "AR-N056",
        "AR-N042",
        "AR-N112",
        "AR-N063",
        "AR-N049",
        "AR-Q035",
        "AR-Q112",
        "AR-Q014",
        "AR-Q091",
        "AR-Q042",
        "AR-Q077",
        "AR-Q084",
        "AR-Q063",
        "AR-Q105",
        "AR-Q007",
        "AR-Q021",
        "AR-Q098",
        "AR-Q028",
        "AR-Q049",
        "AR-Q056",
        "AR-Q070",
        "AR-R007",
        "AR-R028",
        "AR-R077",
        "AR-R084",
        "AR-R049",
        "AR-R091",
        "AR-R056",
        "AR-R070",
        "AR-R021",
        "AR-R063",
        "AR-R014",
        "AR-R042",
        "AR-R035",
        "AR-A028",
        "AR-A077",
        "AR-A049",
        "AR-A112",
        "AR-A007",
        "AR-A133",
        "AR-A126",
        "AR-A056",
        "AR-A070",
        "AR-A161",
        "AR-A035",
        "AR-A042",
        "AR-A098",
        "AR-A063",
        "AR-A140",
        "AR-A084",
        "AR-A021",
        "AR-A154",
        "AR-A119",
        "AR-A014",
        "AR-A147",
        "AR-A091",
        "AR-A105",
        "AR-J028",
        "AR-J098",
        "AR-J042",
        "AR-J084",
        "AR-J133",
        "AR-J077",
        "AR-J434",
        "AR-J091",
        "AR-J014",
        "AR-J007",
        "AR-J112",
        "AR-J070",
        "AR-J105",
        "AR-J126",
        "AR-J035",
        "AR-J119",
        "AR-J056",
        "AR-J049",
        "AR-J021",
        "AR-D056",
        "AR-D021",
        "AR-D035",
        "AR-D028",
        "AR-D063",
        "AR-D049",
        "AR-D007",
        "AR-D014",
        "AR-D042",
        "AR-Z014",
        "AR-Z035",
        "AR-Z042",
        "AR-Z049",
        "AR-Z007",
        "AR-Z028",
        "AR-Z021",
        "AR-S007",
        "AR-S014",
        "AR-S021",
        "AR-S028",
        "AR-S035",
        "AR-S042",
        "AR-S049",
        "AR-S056",
        "AR-S063",
        "AR-S070",
        "AR-S077",
        "AR-S084",
        "AR-S091",
        "AR-S098",
        "AR-S105",
        "AR-S112",
        "AR-S119",
        "AR-S126",
        "AR-S133",
        "AR-G049",
        "AR-G028",
        "AR-G007",
        "AR-G014",
        "AR-G021",
        "AR-G035",
        "AR-G042",
        "AR-G056",
        "AR-G063",
        "AR-G070",
        "AR-G084",
        "AR-G091",
        "AR-G105",
        "AR-G098",
        "AR-G112",
        "AR-G119",
        "AR-G126",
        "AR-G133",
        "AR-G140",
        "AR-G154",
        "AR-G161",
        "AR-G147",
        "AR-G189",
        "AR-G175",
        "AR-G168",
        "AR-G182",
        "AR-G077",
        "AR-T084",
        "AR-T063",
        "AR-T028",
        "AR-T070",
        "AR-T021",
        "AR-T077",
        "AR-T042",
        "AR-T049",
        "AR-T035",
        "AR-T091",
        "AR-T056",
        "AR-T014",
        "AR-T007",
        "AR-T112",
        "AR-T119",
        "AR-T105",
        "AR-T098",
        "AR-V014",
        "AR-V007",
        "AR-BAS-CAMMESA",
        "AR-CEN-CAMMESA",
        "AR-COM-CAMMESA",
        "AR-CUY-CAMMESA",
        "AR-LIT-CAMMESA",
        "AR-NEA-CAMMESA",
        "AR-NOA-CAMMESA",
        "AR-PAT-CAMMESA",
        "AR-NAC",
        "AR-GBA",
        "AR-NOA",
        "AR-NEA",
        "AR-PAM",
        "AR-CUY",
        "AR-PAT",
        "SEBACO_AR-B-RESTO",
        "SEBACO_AR-RESTO",
        "DESIGU_AML",
        "MINERI_NO-DIST",
        "EAS_MPD",
        "EEU_MPD",
        "LAC_MPD",
        "MNA_MPD",
        "SEA_MPD",
        "SSA_MPD",
        "WEU_MPD",
        "WOF_MPD",
        "CRECIM_AML-RESTO",
        "DESHUM_ZZA.VHHD",
        "DESHUM_ZZB.HHD",
        "DESHUM_ZZC.MHD",
        "DESHUM_ZZD.LHD",
        "DESHUM_ZZE.AS",
        "DESHUM_ZZF.EAP",
        "DESHUM_ZZG.ECA",
        "DESHUM_ZZH.LAC",
        "DESHUM_ZZI.SA",
        "DESHUM_ZZJ.SSA",
        "MERTRA_TOTAL",
        "DESHUM_AHDI.EAS",
        "DESHUM_AHDI.EEU",
        "DESHUM_AHDI.LAC",
        "DESHUM_AHDI.MEA",
        "DESHUM_AHDI.NAF",
        "DESHUM_AHDI.OECD",
        "DESHUM_AHDI.ROW",
        "DESHUM_AHDI.SAS",
        "DESHUM_AHDI.SSA",
        "DESHUM_AHDI.WEU",
        "DESHUM_AHDI.WLD",
        "DESHUM_AHDI.WOF"
    ],
    "name_short": [
        "Aruba",
        "\u00c1frica Oriental y Meridional",
        "Afganist\u00e1n",
        "\u00c1frica Occidental y Central",
        "Angola",
        "Anguila",
        "Islas \u00c5land",
        "Albania",
        "Andorra",
        "Antillas Holandesas",
        "Mundo \u00e1rabe",
        "Emiratos \u00c1rabes Unidos",
        "Argentina",
        "Armenia",
        "Samoa Americana",
        "Ant\u00e1rtida",
        "Tierras Australes Francesas",
        "Antigua y Barbuda",
        "Australia",
        "Austria",
        "Azerbaiy\u00e1n",
        "Ant\u00e1rtida Brit\u00e1nica",
        "Burundi",
        "B\u00e9lgica",
        "Benin",
        "Bonaire",
        "Burkina Faso",
        "Bangladesh",
        "Bulgaria",
        "Bahrein",
        "Bahamas",
        "Bosnia y Herzegovina",
        "San Barth\u00e9lemy",
        "Belar\u00fas",
        "B\u00e9lgica-Luxemburgo",
        "Belice",
        "Bermuda",
        "Bolivia",
        "Brasil",
        "Barbados",
        "Brunei",
        "Bhut\u00e1n",
        "Bouvet",
        "Botswana",
        "Rep. Centroafricana",
        "Canad\u00e1",
        "Islas Cocos",
        "Europa Central y B\u00e1lticos",
        "Comunidad Econ\u00f3mica y Monetaria de Africa Central (CEMAC)",
        "Suiza",
        "Islas Del Canal",
        "Chile",
        "China",
        "Costa de Marfil",
        "Camer\u00fan",
        "Rep. Dem. Congo",
        "Congo",
        "Islas Cook",
        "Colombia",
        "Comoras",
        "Cabo Verde",
        "Costa Rica",
        "Checoslovaquia",
        "Peque\u00f1os Estados del Caribe",
        "Cuba",
        "Curazao",
        "Isla Christmas",
        "Islas Caim\u00e1n",
        "Chipre",
        "Chequia",
        "Rep. Dem. Alemana",
        "Alemania",
        "Djibouti",
        "Dominica",
        "Dinamarca",
        "Rep. Dominicana",
        "Argelia",
        "Este de Asia y Pac\u00edfico",
        "Bono demogr\u00e1fico temprano",
        "Este de Asia y Pac\u00edfico",
        "Europa y Asia Central",
        "Europa y Asia Central",
        "Ecuador",
        "Egipto",
        "Eurozona",
        "Eritrea",
        "S\u00e1hara Occidental",
        "Espa\u00f1a",
        "Estonia",
        "Etiop\u00eda (incluye Eritrea)",
        "Etiop\u00eda",
        "Uni\u00f3n Europea",
        "Territorio en Fideicomiso de las Islas del Pac\u00edfico",
        "Sud\u00e1n (Ex)",
        "Sark",
        "Am\u00e9rica del Norte y Central",
        "China",
        "\u00c1frica Subsahariana",
        "Norte de \u00c1frica",
        "\u00c1frica Oriental",
        "\u00c1frica Media",
        "\u00c1frica del Norte",
        "\u00c1frica del Sur",
        "\u00c1frica Occidental",
        "Am\u00e9rica del Norte",
        "Centroam\u00e9rica",
        "Am\u00e9rica Latina y el Caribe",
        "Caribe",
        "Sudam\u00e9rica",
        "Am\u00e9rica del Norte y Europa",
        "Asia",
        "Asia Central",
        "Asia Oriental",
        "Asia del Sur",
        "Sudeste Asi\u00e1tico",
        "Asia Occidental",
        "Asia Central y Asia Meridional",
        "Asia Oriental y Asia Sudoriental",
        "Asia Occidental y \u00c1frica del Norte",
        "Europa del Este",
        "Norte de Europa",
        "Europa del Sur",
        "Europa Oriental",
        "Ocean\u00eda",
        "Australia y Nueva Zelanda",
        "Melanesia",
        "Polinesia",
        "Regi\u00f3n Ant\u00e1rtica",
        "Uni\u00f3n Europea (27)",
        "Pa\u00edses menos desarrollados",
        "Pa\u00edses en desarrollo sin litoral",
        "Peque\u00f1os Estados insulares",
        "Ocean\u00eda (excluyendo Australia y Nueva Zelanda)",
        "\u00c1frica Subsahariana",
        "Pa\u00edses de bajos ingresos",
        "Pa\u00edses en desarrollo importadores netos de alimentos",
        "Asia Oriental (excluido Jap\u00f3n)",
        "Regiones en desarrollo",
        "Regiones desarrolladas",
        "Asia Occidental",
        "Asia Oriental (excluyendo Jap\u00f3n y China)",
        "Pa\u00edses del Anexo I",
        "Pa\u00edses no Incluidos en el Anexo I",
        "Asia Meridional (excluida India)",
        "C\u00e1ucaso y Asia Central",
        "Econom\u00edas de bajos ingresos",
        "Econom\u00edas de ingresos medianos bajos",
        "OCDE",
        "Rep\u00fablica Democr\u00e1tica Popular Etiop\u00eda",
        "Rep\u00fablica Federal de Alemania (ex)",
        "Econom\u00edas de altos ingresos",
        "Econom\u00edas de ingresos medianos y altos",
        "Situaciones fr\u00e1giles y afectadas por conflictos",
        "Finlandia",
        "Fiji",
        "Islas Malvinas",
        "Francia",
        "Zonas francas",
        "Islas Feroe",
        "Micronesia",
        "Gab\u00f3n",
        "Franja de Gaza",
        "Reino Unido",
        "Georgia",
        "Guernsey",
        "Ghana",
        "Gibraltar",
        "Guinea",
        "Guadalupe",
        "Gambia",
        "Guinea-Bissau",
        "Guinea Ecuatorial",
        "Grecia",
        "Granada",
        "Groenlandia",
        "Guatemala",
        "Guayana Francesa",
        "Guam",
        "Guyana",
        "Pa\u00edses de altos ingresos",
        "Hong Kong",
        "Islas Heard y McDonald",
        "Honduras",
        "Pa\u00edses pobres endeudados",
        "Croacia",
        "Hait\u00ed",
        "Hungr\u00eda",
        "S\u00f3lo BIRF",
        "AIF",
        "AIF Total",
        "Mezcla de AIF",
        "Indonesia",
        "Solo AIF",
        "Isla de Man",
        "India",
        "Territorio Brit\u00e1nico del Oc\u00e9ano \u00cdndico",
        "Irlanda",
        "Ir\u00e1n",
        "Iraq",
        "Islandia",
        "Israel",
        "Italia",
        "Jamaica",
        "Jersey",
        "Jordania",
        "Jap\u00f3n",
        "Isla Jhonston",
        "Kazajst\u00e1n",
        "Kenia",
        "Kirguist\u00e1n",
        "Camboya",
        "Kiribati",
        "San Crist\u00f3bal y Nieves-Anguila-Aru",
        "Saint Kitts y Nevis",
        "Corea del Sur",
        "Kuwait",
        "Am\u00e9rica Latina y el Caribe",
        "Laos",
        "L\u00edbano",
        "Liberia",
        "Libia",
        "Santa Luc\u00eda",
        "Am\u00e9rica Latina y el Caribe",
        "Pa\u00edses menos desarrollados",
        "Pa\u00edses de bajos ingresos",
        "Liechtenstein",
        "Sri Lanka",
        "Pa\u00edses de ingreso medio bajo",
        "Pa\u00edses de ingreso bajo y medio",
        "Lesotho",
        "Bono demogr\u00e1fico tard\u00edo",
        "Lituania",
        "Luxemburgo",
        "Letonia",
        "Macao",
        "San Mart\u00edn (parte francesa)",
        "Marruecos",
        "M\u00f3naco",
        "Moldavia",
        "Madagascar",
        "Maldivas",
        "Oriente Medio y \u00c1frica del Norte",
        "M\u00e9xico",
        "Islas Marshall",
        "Pa\u00edses de ingreso medio",
        "Islas Midway",
        "Macedonia del Norte",
        "Mal\u00ed",
        "Malta",
        "Myanmar",
        "Oriente Medio y \u00c1frica del Norte",
        "Montenegro",
        "Mongolia",
        "Islas Marianas",
        "Mozambique",
        "Mauritania",
        "Montserrat",
        "Martinica",
        "Mauricio",
        "Malawi",
        "Malasia",
        "Mayotte",
        "Am\u00e9rica del Norte",
        "Namibia",
        "Nueva Caledonia",
        "N\u00edger",
        "Isla Norfolk",
        "Nigeria",
        "Nicaragua",
        "Niue",
        "Pa\u00edses Bajos",
        "Noruega",
        "Nepal",
        "Nauru",
        "Zona Neutral",
        "Nueva Zelandia",
        "Miembros de la OCDE",
        "Pa\u00edses de altos ingresos",
        "Om\u00e1n",
        "Otros Estados peque\u00f1os",
        "Pakist\u00e1n",
        "Panam\u00e1",
        "Islas del Pac\u00edfico",
        "Pitcairn",
        "Zona del Canal de Panam\u00e1 (ex)",
        "Per\u00fa",
        "Filipinas",
        "Palau",
        "Pen Malasia",
        "Pap\u00faa Nueva Guinea",
        "Polonia",
        "Pa\u00edses del bono predemogr\u00e1fico",
        "Puerto Rico",
        "Corea del Norte",
        "Portugal",
        "Paraguay",
        "Palestina",
        "Peque\u00f1os Estados insulares del Pac\u00edfico",
        "Pa\u00edses del bono posdemogr\u00e1fico",
        "Polinesia Francesa",
        "Qatar",
        "Reuni\u00f3n",
        "Rumania",
        "Rusia",
        "Ruanda",
        "Islas Ry\u016bky\u016b",
        "Asia del Sur",
        "Arabia Saudita",
        "Sab\u00e1",
        "Serbia y Montenegro",
        "Sud\u00e1n",
        "Senegal",
        "Yugoslavia",
        "Singapur",
        "Islas Georgias y Sandwich del Sur",
        "Santa Elena",
        "Sikkim",
        "Islas Svalbard y Jan Mayen",
        "Islas Salom\u00f3n",
        "Sierra Leona",
        "El Salvador",
        "San Marino",
        "Somalia",
        "Categor\u00edas especiales",
        "San Pedro y Miquel\u00f3n",
        "Serbia",
        "\u00c1frica Subsahariana",
        "Sud\u00e1n del Sur",
        "\u00c1frica Subsahariana",
        "Estados peque\u00f1os",
        "Santo Tom\u00e9 y Pr\u00edncipe",
        "Suriname",
        "Eslovaquia",
        "Eslovenia",
        "Vietnam del Sur (ex)",
        "Uni\u00f3n Sovi\u00e9tica",
        "Suecia",
        "Sarawak",
        "Eswatini",
        "San Mart\u00edn (parte holandesa)",
        "Seychelles",
        "Siria",
        "Tanganica (ex)",
        "Islas Turcas y Caicos",
        "Chad",
        "Este de Asia y Pac\u00edfico",
        "Europa y Asia Central",
        "Togo",
        "Tailandia",
        "Tayikist\u00e1n",
        "Tokelau",
        "Turkmenist\u00e1n",
        "Am\u00e9rica Latina y el Caribe",
        "Timor-Leste",
        "Oriente Medio y \u00c1frica del Norte",
        "Tonga",
        "Asia del Sur",
        "\u00c1frica Subsahariana",
        "Trinidad y Tobago",
        "T\u00fanez",
        "Turqu\u00eda",
        "Tuvalu",
        "Taiw\u00e1n",
        "Tanzan\u00eda",
        "Uganda",
        "Ucrania",
        "Pa\u00edses de ingreso medio alto",
        "Islas menores alejadas de EEUU",
        "No especificado",
        "Uruguay",
        "Estados Unidos",
        "Us Msc.Pac.I",
        "Uzbekist\u00e1n",
        "Vaticano",
        "San Vicente y las Granadinas",
        "Vietnam del Norte (ex)",
        "Venezuela",
        "Islas V\u00edrgenes Brit\u00e1nicas",
        "Islas V\u00edrgenes de EEUU",
        "Vietnam",
        "Vanuatu",
        "Isla Wake",
        "Cisjordania y Gaza",
        "Mundo",
        "Wallis y Futuna",
        "Samoa",
        "\u00c1frica",
        "Am\u00e9ricas",
        "Kosovo",
        "Rep. Dem. Pop. Yemen",
        "Yemen",
        "Yemen",
        "Sud\u00e1frica",
        "Zambia",
        "Zanzibar",
        "Rhodesia y Nyasaland (ex)",
        "Zimbabwe",
        "Uni\u00f3n Sovi\u00e9tica",
        "Transporte internacional",
        "Islas del Pac\u00edfico (ex)",
        "Pa\u00edses no declarados",
        "Cooperaci\u00f3n Econ\u00f3mica Asia-Pac\u00edfico",
        "Asociaci\u00f3n de Naciones del Sudeste Asi\u00e1tico",
        "Eurozona",
        "Asia del Este",
        "Uni\u00f3n Europea (28 pa\u00edses excluyendo EU15)",
        "Uni\u00f3n Europea (15 pa\u00edses)",
        "Uni\u00f3n Europea (27 pa\u00edses)",
        "Uni\u00f3n Europea (28 pa\u00edses)",
        "G-20",
        "Pa\u00edses no miembros de OCDE",
        "Pa\u00edses miembros de OCDE",
        "Resto del mundo",
        "Este y Sudeste Asi\u00e1tico",
        "Europa",
        "Am\u00e9rica del Norte",
        "Otras regiones",
        "Am\u00e9rica del Sur y Central",
        "Akrotiri y Dekelia",
        "CABA",
        "Buenos Aires",
        "Catamarca",
        "C\u00f3rdoba",
        "Corrientes",
        "Chaco",
        "Chubut",
        "Entre R\u00edos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuqu\u00e9n",
        "R\u00edo Negro",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Cruz",
        "Santa Fe",
        "Santiago del Estero",
        "Tucum\u00e1n",
        "Tierra del Fuego",
        "Comuna 1 (CABA)",
        "Comuna 2 (CABA)",
        "Comuna 3 (CABA)",
        "Comuna 4 (CABA)",
        "Comuna 5 (CABA)",
        "Comuna 6 (CABA)",
        "Comuna 7 (CABA)",
        "Comuna 8 (CABA)",
        "Comuna 9 (CABA)",
        "Comuna 10 (CABA)",
        "Comuna 11 (CABA)",
        "Comuna 12 (CABA)",
        "Comuna 13 (CABA)",
        "Comuna 14 (CABA)",
        "Comuna 15 (CABA)",
        "Adolfo Alsina (Buenos Aires)",
        "Alberti (Buenos Aires)",
        "Alte. Brown (Buenos Aires)",
        "Avellaneda (Buenos Aires)",
        "Ayacucho (Buenos Aires)",
        "Azul (Buenos Aires)",
        "Bahia Blanca (Buenos Aires)",
        "Balcarce (Buenos Aires)",
        "Baradero (Buenos Aires)",
        "Bartolome Mitre (Buenos Aires)",
        "Berazategui (Buenos Aires)",
        "Berisso (Buenos Aires)",
        "Bolivar (Buenos Aires)",
        "Bragado (Buenos Aires)",
        "Brandsen (Buenos Aires)",
        "Campana (Buenos Aires)",
        "Ca\u00f1uelas (Buenos Aires)",
        "Capitan Sarmiento (Buenos Aires)",
        "Carlos Casares (Buenos Aires)",
        "Carlos Tejedor (Buenos Aires)",
        "Carmen De Areco (Buenos Aires)",
        "Patagones (Buenos Aires)",
        "Castelli (Buenos Aires)",
        "Colon (Buenos Aires)",
        "Cnel. Dorrego (Buenos Aires)",
        "Cnel. Pringles (Buenos Aires)",
        "Cnel. Rosales (Buenos Aires)",
        "Cnel. Su\u00e1rez (Buenos Aires)",
        "Chacabuco (Buenos Aires)",
        "Chascom\u00fas (Buenos Aires)",
        "Chivilcoy (Buenos Aires)",
        "Daireaux (Buenos Aires)",
        "Dolores (Buenos Aires)",
        "Ensenada (Buenos Aires)",
        "Escobar (Buenos Aires)",
        "Esteban Echeverr\u00eda (Buenos Aires)",
        "Exaltaci\u00f3n de la Cruz (Buenos Aires)",
        "Gral. Alvarado (Buenos Aires)",
        "Gral. Alvear (Buenos Aires)",
        "Gral. Arenales (Buenos Aires)",
        "Gral. Belgrano (Buenos Aires)",
        "Gral. Guido (Buenos Aires)",
        "Gral. La Madrid (Buenos Aires)",
        "Gral. Las Heras (Buenos Aires)",
        "Gral. Lavalle (Buenos Aires)",
        "Gral. Juan Madariaga (Buenos Aires)",
        "Gral. Paz (Buenos Aires)",
        "Gral. Pinto (Buenos Aires)",
        "General Pinto (Buenos Aires)",
        "Gral. Pueyrred\u00f3n (Buenos Aires)",
        "Gral. Rodr\u00edguez (Buenos Aires)",
        "Gral. San Mart\u00edn (Buenos Aires)",
        "San Miguel (Buenos Aires)",
        "Gral. Viamonte (Buenos Aires)",
        "Gral. Villegas (Buenos Aires)",
        "Adolfo Gonz\u00e1lez Chaves (Buenos Aires)",
        "Guamin\u00ed (Buenos Aires)",
        "Hip\u00f3lito Yrigoyen (Buenos Aires)",
        "Benito Ju\u00e1rez (Buenos Aires)",
        "Jun\u00edn (Buenos Aires)",
        "La Matanza (Buenos Aires)",
        "Lan\u00fas (Buenos Aires)",
        "La Plata (Buenos Aires)",
        "Laprida (Buenos Aires)",
        "Las Flores (Buenos Aires)",
        "Leandro N. Alem (Buenos Aires)",
        "Lincoln (Buenos Aires)",
        "Lober\u00eda (Buenos Aires)",
        "Lobos (Buenos Aires)",
        "Lomas de Zamora (Buenos Aires)",
        "Luj\u00e1n (Buenos Aires)",
        "Magdalena (Buenos Aires)",
        "Maip\u00fa (Buenos Aires)",
        "Mar Chiquita (Buenos Aires)",
        "Marcos Paz (Buenos Aires)",
        "Mercedes (Buenos Aires)",
        "Merlo (Buenos Aires)",
        "Monte (Buenos Aires)",
        "Moreno (Buenos Aires)",
        "Mor\u00f3n (Buenos Aires)",
        "Navarro (Buenos Aires)",
        "Necochea (Buenos Aires)",
        "9 De Julio (Buenos Aires)",
        "Olavarr\u00eda (Buenos Aires)",
        "Pehuaj\u00f3 (Buenos Aires)",
        "Pellegrini (Buenos Aires)",
        "Pergamino (Buenos Aires)",
        "Pila (Buenos Aires)",
        "Pilar (Buenos Aires)",
        "Pinamar (Buenos Aires)",
        "Pu\u00e1n (Buenos Aires)",
        "Quilmes (Buenos Aires)",
        "Ramallo (Buenos Aires)",
        "Rauch (Buenos Aires)",
        "Rivadavia (Buenos Aires)",
        "Rojas (Buenos Aires)",
        "Roque P\u00e9rez (Buenos Aires)",
        "Saavedra (Buenos Aires)",
        "Saladillo (Buenos Aires)",
        "Salliquel\u00f3 (Buenos Aires)",
        "Salto (Buenos Aires)",
        "San Andr\u00e9s de Giles (Buenos Aires)",
        "San Antonio De Areco (Buenos Aires)",
        "San Cayetano (Buenos Aires)",
        "San Fernando (Buenos Aires)",
        "San Isidro (Buenos Aires)",
        "San Nicol\u00e1s (Buenos Aires)",
        "San Pedro (Buenos Aires)",
        "San Vicente (Buenos Aires)",
        "Suipacha (Buenos Aires)",
        "Tandil (Buenos Aires)",
        "Tapalqu\u00e9 (Buenos Aires)",
        "Tigre (Buenos Aires)",
        "Tornquist (Buenos Aires)",
        "Trenque Lauquen (Buenos Aires)",
        "Tordillo (Buenos Aires)",
        "Tres Arroyos (Buenos Aires)",
        "Tres de Febrero (Buenos Aires)",
        "La Costa (Buenos Aires)",
        "Monte Hermoso (Buenos Aires)",
        "25 De Mayo (Buenos Aires)",
        "Vicente L\u00f3pez (Buenos Aires)",
        "Villa Gesell (Buenos Aires)",
        "Villarino (Buenos Aires)",
        "Z\u00e1rate (Buenos Aires)",
        "Tres Lomas (Buenos Aires)",
        "Florentino Ameghino (Buenos Aires)",
        "Presidente Per\u00f3n (Buenos Aires)",
        "Jos\u00e9 C. Paz (Buenos Aires)",
        "Malvinas Argentinas (Buenos Aires)",
        "Punta Indio (Buenos Aires)",
        "Ezeiza (Buenos Aires)",
        "Ituzainig\u00f3 (Buenos Aires)",
        "Hurlingham (Buenos Aires)",
        "Lezama (Buenos Aires)",
        "Capital (Catamarca)",
        "Capay\u00e1n (Catamarca)",
        "La Paz (Catamarca)",
        "Ancasti (Catamarca)",
        "El Alto (Catamarca)",
        "Santa Rosa (Catamarca)",
        "Pacl\u00edn (Catamarca)",
        "Valle Viejo (Catamarca)",
        "Fray Mamerto Esqui\u00fa (Catamarca)",
        "Ambato (Catamarca)",
        "Pom\u00e1n (Catamarca)",
        "Andalgal\u00e1 (Catamarca)",
        "Bel\u00e9n (Catamarca)",
        "Antofagasta de la Sierra (Catamarca)",
        "Tinogasta (Catamarca)",
        "Santa Mar\u00eda (Catamarca)",
        "Capital (C\u00f3rdoba)",
        "Calamuchita (C\u00f3rdoba)",
        "Col\u00f3n (C\u00f3rdoba)",
        "Cruz del Eje (C\u00f3rdoba)",
        "Gral. Roca (C\u00f3rdoba)",
        "Gral. San Mart\u00edn (C\u00f3rdoba)",
        "Ischil\u00edn (C\u00f3rdoba)",
        "Ju\u00e1rez Celman (C\u00f3rdoba)",
        "Marcos Ju\u00e1rez (C\u00f3rdoba)",
        "Minas (C\u00f3rdoba)",
        "Pocho (C\u00f3rdoba)",
        "Punilla (C\u00f3rdoba)",
        "R\u00edo Cuarto (C\u00f3rdoba)",
        "R\u00edo Primero (C\u00f3rdoba)",
        "R\u00edo Seco (C\u00f3rdoba)",
        "R\u00edo Segundo (C\u00f3rdoba)",
        "Pte. Roque S\u00e1enz Pe\u00f1a (C\u00f3rdoba)",
        "San Alberto (C\u00f3rdoba)",
        "San Javier (C\u00f3rdoba)",
        "San Justo (C\u00f3rdoba)",
        "Santa Maria (C\u00f3rdoba)",
        "Sobremonte (C\u00f3rdoba)",
        "Tercero Arriba (C\u00f3rdoba)",
        "Totoral (C\u00f3rdoba)",
        "Tulumba (C\u00f3rdoba)",
        "Union (C\u00f3rdoba)",
        "Capital (Corrientes)",
        "Goya (Corrientes)",
        "Curuz\u00fa Cuati\u00e1 (Corrientes)",
        "Mercedes (Corrientes)",
        "Esquina (Corrientes)",
        "Lavalle (Corrientes)",
        "Santo Tom\u00e9 (Corrientes)",
        "Paso de los Libres (Corrientes)",
        "Monte Caseros (Corrientes)",
        "San Luis del Palmar (Corrientes)",
        "Bella Vista (Corrientes)",
        "Empedrado (Corrientes)",
        "San Roque (Corrientes)",
        "Gral. Paz (Corrientes)",
        "Saladas (Corrientes)",
        "San Mart\u00edn (Corrientes)",
        "Concepci\u00f3n (Corrientes)",
        "Mburucuy\u00e1 (Corrientes)",
        "Ituzaing\u00f3 (Corrientes)",
        "Sauce (Corrientes)",
        "San Cosme (Corrientes)",
        "Gral. Alvear (Corrientes)",
        "San Miguel (Corrientes)",
        "Itat\u00ed (Corrientes)",
        "Ber\u00f3n de Astrada (Corrientes)",
        "San Fernando (Chaco)",
        "1\u00b0 De Mayo (Chaco)",
        "Libertad (Chaco)",
        "Gral. Donovan (Chaco)",
        "Sargento Cabral (Chaco)",
        "Presidencia de la Plaza (Chaco)",
        "Bermejo (Chaco)",
        "Libertador Gral. San Mart\u00edn (Chaco)",
        "Tapenaga (Chaco)",
        "San Lorenzo (Chaco)",
        "Mayor Luis J. Fontana (Chaco)",
        "O'Higgins (Chaco)",
        "Comandante Fern\u00e1ndez (Chaco)",
        "Quitilipi (Chaco)",
        "25 de Mayo (Chaco)",
        "Maip\u00fa (Chaco)",
        "Independencia (Chaco)",
        "Gral. Belgrano (Chaco)",
        "9 de Julio (Chaco)",
        "Chacabuco (Chaco)",
        "12 de Octubre (Chaco)",
        "2 de Abril (Chaco)",
        "Fray Justo S. M. de Oro (Chaco)",
        "Alte. Brown (Chaco)",
        "Gral. G\u00fcemes (Chaco)",
        "Rawson (Chubut)",
        "Biedma (Chubut)",
        "Telsen (Chubut)",
        "Gastre (Chubut)",
        "Cushamen (Chubut)",
        "Futaleuf\u00fa (Chubut)",
        "Langui\u00f1eo (Chubut)",
        "Tehuelches (Chubut)",
        "Paso de los Indios (Chubut)",
        "M\u00e1rtires (Chubut)",
        "Florentino Ameghino (Chubut)",
        "Gaiman (Chubut)",
        "v",
        "Sarmiento (Chubut)",
        "Escalante (Chubut)",
        "Paran\u00e1 (Entre R\u00edos)",
        "La Paz (Entre R\u00edos)",
        "Diamante (Entre R\u00edos)",
        "Victoria (Entre R\u00edos)",
        "Nogoy\u00e1 (Entre R\u00edos)",
        "Gualeguay (Entre R\u00edos)",
        "Tala (Entre R\u00edos)",
        "Uruguay (Entre R\u00edos)",
        "Gualeguaych\u00fa (Entre R\u00edos)",
        "Islas del Ibicuy (Entre R\u00edos)",
        "Villaguay (Entre R\u00edos)",
        "Concordia (Entre R\u00edos)",
        "Federal (Entre R\u00edos)",
        "Col\u00f3n (Entre R\u00edos)",
        "Feliciano (Entre R\u00edos)",
        "Federaci\u00f3n (Entre R\u00edos)",
        "San Salvador (Entre R\u00edos)",
        "Formosa (Formosa)",
        "Laishi (Formosa)",
        "Pilcomayo (Formosa)",
        "Piran\u00e9 (Formosa)",
        "Pilag\u00e1s (Formosa)",
        "Pati\u00f1o (Formosa)",
        "Bermejo (Formosa)",
        "Matacos (Formosa)",
        "Ram\u00f3n Lista (Formosa)",
        "Dr. Manuel Belgrano (Jujuy)",
        "Palpal\u00e1 (Jujuy)",
        "San Antonio (Jujuy)",
        "El Carmen (Jujuy)",
        "San Pedro (Jujuy)",
        "Santa B\u00e1rbara (Jujuy)",
        "Ledesma (Jujuy)",
        "Valle Grande (Jujuy)",
        "Tumbaya (Jujuy)",
        "Tilcara (Jujuy)",
        "Humahuaca (Jujuy)",
        "Cochinoca (Jujuy)",
        "Rinconada (Jujuy)",
        "Santa Catalina (Jujuy)",
        "Yavi (Jujuy)",
        "Susques (Jujuy)",
        "Atreuc\u00f3 (La Pampa)",
        "Capital (La Pampa)",
        "Caleu Caleu (La Pampa)",
        "Catril\u00f3 (La Pampa)",
        "Chalileo (La Pampa)",
        "Chapaleuf\u00fa (La Pampa)",
        "Chical Co (La Pampa)",
        "Conhelo (La Pampa)",
        "Curac\u00f3 (La Pampa)",
        "Guatrach\u00e9 (La Pampa)",
        "Hucal (La Pampa)",
        "Loventu\u00e9 (La Pampa)",
        "Lihuel Calel (La Pampa)",
        "Limay Mahuida (La Pampa)",
        "Marac\u00f3 (La Pampa)",
        "Puel\u00e9n (La Pampa)",
        "Quem\u00fa Quem\u00fa (La Pampa)",
        "Rancul (La Pampa)",
        "Realic\u00f3 (La Pampa)",
        "Toay (La Pampa)",
        "Trenel (La Pampa)",
        "Utrac\u00e1n (La Pampa)",
        "Capital (La Rioja)",
        "Sanagasta (La Rioja)",
        "Castro Barros (La Rioja)",
        "Arauco (La Rioja)",
        "San Blas de los Sauces (La Rioja)",
        "Chilecito (La Rioja)",
        "Famatina (La Rioja)",
        "Cnel. Felipe Varela (La Rioja)",
        "General Lamadrid (La Rioja)",
        "Vinchina (La Rioja)",
        "Independencia (La Rioja)",
        "Chamical (La Rioja)",
        "Gral. Angel V. Pe\u00f1aloza (La Rioja)",
        "Gral. Belgrano (La Rioja)",
        "Gral. Juan F. Quiroga (La Rioja)",
        "Gral. Ocampo (La Rioja)",
        "Rosario Vera Pe\u00f1aloza (La Rioja)",
        "Gral. San Mart\u00edn (La Rioja)",
        "Capital (Mendoza)",
        "Godoy Cruz (Mendoza)",
        "Guaymall\u00e9n (Mendoza)",
        "Las Heras (Mendoza)",
        "Lavalle (Mendoza)",
        "Maip\u00fa (Mendoza)",
        "Luj\u00e1n de Cuyo (Mendoza)",
        "Tupungato (Mendoza)",
        "San Mart\u00edn (Mendoza)",
        "Jun\u00edn (Mendoza)",
        "Rivadavia (Mendoza)",
        "Tunuy\u00e1n (Mendoza)",
        "San Carlos (Mendoza)",
        "Santa Rosa (Mendoza)",
        "La Paz (Mendoza)",
        "San Rafael (Mendoza)",
        "Malarg\u00fce (Mendoza)",
        "Gral. Alvear (Mendoza)",
        "Capital (Misiones)",
        "Ap\u00f3stoles (Misiones)",
        "Candelaria (Misiones)",
        "Leandro N. Alem (Misiones)",
        "Concepcion (Misiones)",
        "San Javier (Misiones)",
        "San Ignacio (Misiones)",
        "Ober\u00e1 (Misiones)",
        "Libertador Gral. San Mart\u00edn (Misiones)",
        "Caingu\u00e1s (Misiones)",
        "25 de Mayo (Misiones)",
        "Montecarlo (Misiones)",
        "Guaran\u00ed (Misiones)",
        "El Dorado (Misiones)",
        "San Pedro (Misiones)",
        "Iguaz\u00fa (Misiones)",
        "Gral. Manuel Belgrano (Misiones)",
        "Confluencia (Neuqu\u00e9n)",
        "Zapala (Neuqu\u00e9n)",
        "A\u00f1elo (Neuqu\u00e9n)",
        "Pehuenches (Neuqu\u00e9n)",
        "Chos Malal (Neuqu\u00e9n)",
        "Minas (Neuqu\u00e9n)",
        "\u00d1orqu\u00edn (Neuqu\u00e9n)",
        "Loncopu\u00e9 (Neuqu\u00e9n)",
        "Picunches (Neuqu\u00e9n)",
        "Alumin\u00e9 (Neuqu\u00e9n)",
        "Catan Lil (Neuqu\u00e9n)",
        "Pic\u00fan Leuf\u00fa (Neuqu\u00e9n)",
        "Collon Cur\u00e1 (Neuqu\u00e9n)",
        "Huiliches (Neuqu\u00e9n)",
        "L\u00e1car (Neuqu\u00e9n)",
        "Los Lagos (Neuqu\u00e9n)",
        "Adolfo Alsina (R\u00edo Negro)",
        "Conesa (R\u00edo Negro)",
        "San Antonio (R\u00edo Negro)",
        "Valcheta (R\u00edo Negro)",
        "9 de Julio (R\u00edo Negro)",
        "25 de Mayo (R\u00edo Negro)",
        "\u00d1orquinco (R\u00edo Negro)",
        "Pilcaniyeu (R\u00edo Negro)",
        "Bariloche (R\u00edo Negro)",
        "Pichi Mahuida (R\u00edo Negro)",
        "Avellaneda (R\u00edo Negro)",
        "Gral. Roca (R\u00edo Negro)",
        "El Cuy (R\u00edo Negro)",
        "Capital (Salta)",
        "La Caldera (Salta)",
        "Gral. G\u00fcemes (Salta)",
        "Met\u00e1n (Salta)",
        "Anta (Salta)",
        "Rivadavia (Salta)",
        "Or\u00e1n (Salta)",
        "Gral. Jose de San Mart\u00edn (Salta)",
        "Iruya (Salta)",
        "Santa Victoria (Salta)",
        "Cerrillos (Salta)",
        "Chicoana (Salta)",
        "La Vi\u00f1a (Salta)",
        "Guachipas (Salta)",
        "Rosario de la Frontera (Salta)",
        "La Candelaria (Salta)",
        "Cafayate (Salta)",
        "San Carlos (Salta)",
        "Molinos (Salta)",
        "Cachi (Salta)",
        "Rosario de Lerma (Salta)",
        "La Poma (Salta)",
        "Los Andes (Salta)",
        "Capital (San Juan)",
        "Santa Luc\u00eda (San Juan)",
        "Chimbas (San Juan)",
        "Rivadavia (San Juan)",
        "Zonda (San Juan)",
        "Rawson (San Juan)",
        "9 de Julio (San Juan)",
        "San Mart\u00edn (San Juan)",
        "Angaco (San Juan)",
        "Albard\u00f3n (San Juan)",
        "Ullum (San Juan)",
        "Pocito (San Juan)",
        "Sarmiento (San Juan)",
        "25 de Mayo (San Juan)",
        "Caucete (San Juan)",
        "Valle F\u00e9rtil (San Juan)",
        "J\u00e1chal (San Juan)",
        "Iglesia (San Juan)",
        "Calingasta (San Juan)",
        "La Capital (San Luis)",
        "Coronel Pringles (San Luis)",
        "Gral. Pedernera (San Luis)",
        "Chacabuco (San Luis)",
        "Libertador Gral. San Mart\u00edn (San Luis)",
        "Jun\u00edn (San Luis)",
        "Ayacucho (San Luis)",
        "Belgrano (San Luis)",
        "Gobernador Dupuy (San Luis)",
        "Deseado (Santa Cruz)",
        "Lago Buenos Aires (Santa Cruz)",
        "Magallanes (Santa Cruz)",
        "R\u00edo Chico (Santa Cruz)",
        "Corpen Aike (Santa Cruz)",
        "Lago Argentino (Santa Cruz)",
        "G\u00fcer Aike (Santa Cruz)",
        "Belgrano (Santa Fe)",
        "Caseros (Santa Fe)",
        "Castellanos (Santa Fe)",
        "Constituci\u00f3n (Santa Fe)",
        "Garay (Santa Fe)",
        "Gral. L\u00f3pez (Santa Fe)",
        "General Obligado (Santa Fe)",
        "Iriondo (Santa Fe)",
        "La Capital (Santa Fe)",
        "Las Colonias (Santa Fe)",
        "9 de Julio (Santa Fe)",
        "Rosario (Santa Fe)",
        "San Crist\u00f3bal (Santa Fe)",
        "San Javier (Santa Fe)",
        "San Jer\u00f3nimo (Santa Fe)",
        "San Justo (Santa Fe)",
        "San Lorenzo (Santa Fe)",
        "San Martin (Santa Fe)",
        "Vera (Santa Fe)",
        "Capital (Santiago del Estero)",
        "Avellaneda (Santiago del Estero)",
        "Aguirre (Santiago del Estero)",
        "Alberdi (Santiago del Estero)",
        "Atamisqui (Santiago del Estero)",
        "Banda (Santiago del Estero)",
        "Belgrano (Santiago del Estero)",
        "Copo (Santiago del Estero)",
        "Choya (Santiago del Estero)",
        "Figueroa (Santiago del Estero)",
        "Guasay\u00e1n (Santiago del Estero)",
        "Jim\u00e9nez (Santiago del Estero)",
        "Loreto (Santiago del Estero)",
        "Juan F. Ibarra (Santiago del Estero)",
        "Mitre (Santiago del Estero)",
        "Moreno (Santiago del Estero)",
        "Ojo de Agua (Santiago del Estero)",
        "Pellegrini (Santiago del Estero)",
        "Quebrachos (Santiago del Estero)",
        "Rivadavia (Santiago del Estero)",
        "Robles (Santiago del Estero)",
        "R\u00edo Hondo (Santiago del Estero)",
        "Silipica (Santiago del Estero)",
        "San Mart\u00edn (Santiago del Estero)",
        "Salavina (Santiago del Estero)",
        "Sarmiento (Santiago del Estero)",
        "Gral. Taboada (Santiago del Estero)",
        "Capital (Tucum\u00e1n)",
        "Lules (Tucum\u00e1n)",
        "Famaill\u00e1 (Tucum\u00e1n)",
        "Monteros (Tucum\u00e1n)",
        "Chicligasta (Tucum\u00e1n)",
        "R\u00edo Chico (Tucum\u00e1n)",
        "Juan B. Alberdi (Tucum\u00e1n)",
        "La Cocha (Tucum\u00e1n)",
        "Graneros (Tucum\u00e1n)",
        "Simoca (Tucum\u00e1n)",
        "Leales (Tucum\u00e1n)",
        "Cruz Alta (Tucum\u00e1n)",
        "Burruyac\u00fa (Tucum\u00e1n)",
        "Trancas (Tucum\u00e1n)",
        "Yerba Buena (Tucum\u00e1n)",
        "Taf\u00ed Viejo (Tucum\u00e1n)",
        "Taf\u00ed Del Valle (Tucum\u00e1n)",
        "Ushuaia (Tierra del Fuego)",
        "R\u00edo Grande (Tierra del Fuego)",
        "CABA y Buenos Aires",
        "Centro",
        "Comahue",
        "Cuyo",
        "Litoral",
        "NEA",
        "NOA",
        "Patagonia",
        "Nacional",
        "Gran Buenos Aires",
        "NOA",
        "NEA",
        "Pampeana",
        "Cuyo",
        "Patagonia",
        "Resto de Buenos Aires",
        "Resto del pa\u00eds",
        "Am\u00e9rica Latina",
        "No distribu\u00eddo",
        "Asia Oriental",
        "Europa Oriental",
        "Am\u00e9rica Latina",
        "Medio Oriente y \u00c1frica del Norte",
        "Asia del Sur y Sudeste",
        "\u00c1frica Subsahariana",
        "Europa Occidental",
        "Ramificaciones de Occidente",
        "Resto de Am\u00e9rica Latina",
        "Pa\u00edses de desarrollo humano muy alto",
        "Pa\u00edses de desarrollo humano alto",
        "Pa\u00edses de desarrollo humano medio",
        "Pa\u00edses de desarrollo humano bajo",
        "Estados \u00e1rabes",
        "Este de Asia y Pac\u00edfico",
        "Europa y Asia Central",
        "Am\u00e9rica Latina y el Caribe",
        "Asia meridional",
        "\u00c1frica Subsahariana",
        "Total",
        "Asia Oriental",
        "Europa Oriental",
        "Am\u00e9rica Latina y el Caribe",
        "Medio Oriente",
        "\u00c1frica del Norte",
        "Pa\u00edses de la OCDE",
        "Pa\u00edses no OCDE",
        "Asia del Sur",
        "\u00c1frica Subsahariana",
        "Europa Occidental",
        "Mundo",
        "Ramificaciones de Occidente"
    ]
})

    df = df.merge(geonomenclador[['geocodigo', 'name_short']], left_on=col, right_on='geocodigo', how='left')
    df = df.drop(columns=['geocodigo'])
    return df

@transformer.convert
def drop_col(df: DataFrame, col, axis=1):
    return df.drop(col, axis=axis)

@transformer.convert
def drop_col(df: DataFrame, col, axis=1):
    return df.drop(col, axis=axis)

@transformer.convert
def rename_cols(df: DataFrame, map):
    df = df.rename(columns=map)
    return df

@transformer.convert
def multiplicar_por_escalar(df: DataFrame, col:str, k:float):
    df[col] = df[col]*k
    return df
#  DEFINITIONS_END


#  PIPELINE_START
pipeline = chain(
query(condition='anio == anio.max()'),
	drop_col(col='anio', axis=1),
	add_nombre_corto(col='provincia_id'),
	drop_col(col='vab_pb', axis=1),
	drop_col(col='provincia_id', axis=1),
	rename_cols(map={'name_short': 'nivel2', 'region': 'nivel1', 'participacion': 'valor'}),
	multiplicar_por_escalar(col='valor', k=100)
)
#  PIPELINE_END


#  start()
#  RangeIndex: 456 entries, 0 to 455
#  Data columns (total 5 columns):
#   #   Column         Non-Null Count  Dtype  
#  ---  ------         --------------  -----  
#   0   anio           456 non-null    int64  
#   1   vab_pb         456 non-null    float64
#   2   region         456 non-null    object 
#   3   participacion  456 non-null    float64
#   4   provincia_id   456 non-null    object 
#  
#  |    |   anio |   vab_pb | region          |   participacion | provincia_id   |
#  |---:|-------:|---------:|:----------------|----------------:|:---------------|
#  |  0 |   2004 |   131866 | Pampeana y AMBA |        0.319959 | AR-B           |
#  
#  ------------------------------
#  
#  query(condition='anio == anio.max()')
#  Index: 24 entries, 18 to 455
#  Data columns (total 5 columns):
#   #   Column         Non-Null Count  Dtype  
#  ---  ------         --------------  -----  
#   0   anio           24 non-null     int64  
#   1   vab_pb         24 non-null     float64
#   2   region         24 non-null     object 
#   3   participacion  24 non-null     float64
#   4   provincia_id   24 non-null     object 
#  
#  |    |   anio |   vab_pb | region          |   participacion | provincia_id   |
#  |---:|-------:|---------:|:----------------|----------------:|:---------------|
#  | 18 |   2022 |   196497 | Pampeana y AMBA |        0.325324 | AR-B           |
#  
#  ------------------------------
#  
#  drop_col(col='anio', axis=1)
#  Index: 24 entries, 18 to 455
#  Data columns (total 4 columns):
#   #   Column         Non-Null Count  Dtype  
#  ---  ------         --------------  -----  
#   0   vab_pb         24 non-null     float64
#   1   region         24 non-null     object 
#   2   participacion  24 non-null     float64
#   3   provincia_id   24 non-null     object 
#  
#  |    |   vab_pb | region          |   participacion | provincia_id   |
#  |---:|---------:|:----------------|----------------:|:---------------|
#  | 18 |   196497 | Pampeana y AMBA |        0.325324 | AR-B           |
#  
#  ------------------------------
#  
#  add_nombre_corto(col='provincia_id')
#  RangeIndex: 24 entries, 0 to 23
#  Data columns (total 5 columns):
#   #   Column         Non-Null Count  Dtype  
#  ---  ------         --------------  -----  
#   0   vab_pb         24 non-null     float64
#   1   region         24 non-null     object 
#   2   participacion  24 non-null     float64
#   3   provincia_id   24 non-null     object 
#   4   name_short     24 non-null     object 
#  
#  |    |   vab_pb | region          |   participacion | provincia_id   | name_short   |
#  |---:|---------:|:----------------|----------------:|:---------------|:-------------|
#  |  0 |   196497 | Pampeana y AMBA |        0.325324 | AR-B           | Buenos Aires |
#  
#  ------------------------------
#  
#  drop_col(col='vab_pb', axis=1)
#  RangeIndex: 24 entries, 0 to 23
#  Data columns (total 4 columns):
#   #   Column         Non-Null Count  Dtype  
#  ---  ------         --------------  -----  
#   0   region         24 non-null     object 
#   1   participacion  24 non-null     float64
#   2   provincia_id   24 non-null     object 
#   3   name_short     24 non-null     object 
#  
#  |    | region          |   participacion | provincia_id   | name_short   |
#  |---:|:----------------|----------------:|:---------------|:-------------|
#  |  0 | Pampeana y AMBA |        0.325324 | AR-B           | Buenos Aires |
#  
#  ------------------------------
#  
#  drop_col(col='provincia_id', axis=1)
#  RangeIndex: 24 entries, 0 to 23
#  Data columns (total 3 columns):
#   #   Column         Non-Null Count  Dtype  
#  ---  ------         --------------  -----  
#   0   region         24 non-null     object 
#   1   participacion  24 non-null     float64
#   2   name_short     24 non-null     object 
#  
#  |    | region          |   participacion | name_short   |
#  |---:|:----------------|----------------:|:-------------|
#  |  0 | Pampeana y AMBA |        0.325324 | Buenos Aires |
#  
#  ------------------------------
#  
#  rename_cols(map={'name_short': 'nivel2', 'region': 'nivel1', 'participacion': 'valor'})
#  RangeIndex: 24 entries, 0 to 23
#  Data columns (total 3 columns):
#   #   Column  Non-Null Count  Dtype  
#  ---  ------  --------------  -----  
#   0   nivel1  24 non-null     object 
#   1   valor   24 non-null     float64
#   2   nivel2  24 non-null     object 
#  
#  |    | nivel1          |   valor | nivel2       |
#  |---:|:----------------|--------:|:-------------|
#  |  0 | Pampeana y AMBA | 32.5324 | Buenos Aires |
#  
#  ------------------------------
#  
#  multiplicar_por_escalar(col='valor', k=100)
#  RangeIndex: 24 entries, 0 to 23
#  Data columns (total 3 columns):
#   #   Column  Non-Null Count  Dtype  
#  ---  ------  --------------  -----  
#   0   nivel1  24 non-null     object 
#   1   valor   24 non-null     float64
#   2   nivel2  24 non-null     object 
#  
#  |    | nivel1          |   valor | nivel2       |
#  |---:|:----------------|--------:|:-------------|
#  |  0 | Pampeana y AMBA | 32.5324 | Buenos Aires |
#  
#  ------------------------------
#  